// Code generated by goyacc -o scanner/strace.go -p Strace scanner/strace.y. DO NOT EDIT.

//line scanner/strace.y:2
package scanner

import __yyfmt__ "fmt"

//line scanner/strace.y:2

import (
	types "github.com/shankarapailoor/moonshine/strace_types"
	//"fmt"
)

//line scanner/strace.y:12
type StraceSymType struct {
	yys               int
	data              string
	val_int           int64
	val_double        float64
	val_uint          uint64
	val_field         *types.Field
	val_call          *types.Call
	val_macro         *types.Macro
	val_int_type      *types.IntType
	val_identifiers   []*types.BufferType
	val_buf_type      *types.BufferType
	val_struct_type   *types.StructType
	val_array_type    *types.ArrayType
	val_pointer_type  *types.PointerType
	val_flag_type     *types.FlagType
	val_type          types.Type
	val_ip_type       *types.IpType
	val_types         []types.Type
	val_parenthetical *types.Parenthetical
	val_syscall       *types.Syscall
}

const STRING_LITERAL = 57346
const IPV4 = 57347
const IPV6 = 57348
const IDENTIFIER = 57349
const FLAG = 57350
const DATETIME = 57351
const SIGNAL_PLUS = 57352
const SIGNAL_MINUS = 57353
const MAC = 57354
const INT = 57355
const UINT = 57356
const DOUBLE = 57357
const QUESTION = 57358
const ARROW = 57359
const OR = 57360
const AND = 57361
const LOR = 57362
const TIMES = 57363
const LAND = 57364
const LEQUAL = 57365
const ONESCOMP = 57366
const LSHIFT = 57367
const RSHIFT = 57368
const NOT = 57369
const COMMA = 57370
const LBRACKET = 57371
const RBRACKET = 57372
const LBRACKET_SQUARE = 57373
const RBRACKET_SQUARE = 57374
const LPAREN = 57375
const RPAREN = 57376
const EQUALS = 57377
const UNFINISHED = 57378
const RESUMED = 57379
const NULL = 57380
const AT = 57381
const COLON = 57382
const KEYWORD = 57383
const NOTYPE = 57384
const NOFLAG = 57385
const EQUAL = 57386

var StraceToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING_LITERAL",
	"IPV4",
	"IPV6",
	"IDENTIFIER",
	"FLAG",
	"DATETIME",
	"SIGNAL_PLUS",
	"SIGNAL_MINUS",
	"MAC",
	"INT",
	"UINT",
	"DOUBLE",
	"QUESTION",
	"ARROW",
	"OR",
	"AND",
	"LOR",
	"TIMES",
	"LAND",
	"LEQUAL",
	"ONESCOMP",
	"LSHIFT",
	"RSHIFT",
	"NOT",
	"COMMA",
	"LBRACKET",
	"RBRACKET",
	"LBRACKET_SQUARE",
	"RBRACKET_SQUARE",
	"LPAREN",
	"RPAREN",
	"EQUALS",
	"UNFINISHED",
	"RESUMED",
	"NULL",
	"AT",
	"COLON",
	"KEYWORD",
	"NOTYPE",
	"NOFLAG",
	"EQUAL",
}

var StraceStatenames = [...]string{}

const StraceEofCode = 1
const StraceErrCode = 2
const StraceInitialStackSize = 16

//line yacctab:1
var StraceExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const StracePrivate = 57344

const StraceLast = 886

var StraceAct = [...]uint8{
	33, 139, 106, 123, 60, 13, 61, 13, 138, 124,
	47, 62, 14, 35, 14, 8, 121, 2, 37, 38,
	57, 41, 47, 4, 9, 108, 13, 13, 117, 59,
	69, 107, 98, 14, 14, 60, 34, 61, 32, 83,
	65, 67, 62, 79, 78, 47, 36, 3, 47, 13,
	13, 76, 148, 75, 46, 151, 14, 14, 45, 131,
	149, 122, 13, 13, 13, 147, 145, 71, 112, 14,
	14, 14, 84, 85, 77, 13, 94, 104, 35, 44,
	152, 163, 14, 37, 38, 150, 95, 97, 130, 103,
	146, 144, 161, 111, 59, 160, 158, 142, 13, 113,
	13, 24, 13, 32, 47, 14, 74, 14, 99, 14,
	73, 36, 140, 5, 140, 100, 56, 101, 110, 49,
	50, 118, 56, 119, 55, 84, 51, 52, 70, 126,
	127, 140, 128, 49, 50, 53, 56, 54, 55, 63,
	51, 52, 129, 140, 140, 140, 64, 140, 141, 102,
	141, 140, 109, 140, 114, 115, 140, 116, 140, 140,
	140, 140, 140, 140, 140, 140, 124, 141, 140, 125,
	140, 140, 56, 140, 55, 16, 51, 52, 12, 141,
	141, 141, 30, 141, 29, 80, 81, 141, 82, 141,
	154, 31, 141, 15, 141, 141, 141, 141, 141, 141,
	141, 141, 143, 154, 141, 10, 141, 141, 56, 141,
	37, 38, 51, 52, 11, 154, 1, 154, 17, 154,
	0, 39, 154, 0, 154, 0, 0, 154, 0, 154,
	154, 155, 154, 157, 0, 159, 50, 58, 56, 162,
	55, 164, 51, 52, 0, 0, 0, 167, 0, 169,
	170, 72, 172, 48, 49, 50, 53, 56, 54, 55,
	0, 51, 52, 0, 0, 0, 0, 0, 86, 87,
	88, 89, 90, 91, 92, 93, 0, 0, 58, 19,
	26, 27, 21, 35, 20, 0, 0, 28, 37, 38,
	0, 0, 0, 0, 22, 0, 0, 0, 0, 18,
	0, 0, 0, 0, 25, 0, 24, 0, 32, 43,
	0, 40, 42, 23, 0, 0, 36, 19, 26, 27,
	21, 35, 20, 0, 0, 28, 37, 38, 0, 0,
	0, 0, 22, 0, 0, 0, 0, 18, 0, 0,
	0, 0, 25, 0, 24, 0, 32, 7, 0, 6,
	0, 23, 0, 0, 36, 19, 26, 27, 21, 35,
	20, 0, 0, 28, 37, 38, 0, 0, 0, 0,
	22, 0, 0, 0, 0, 18, 0, 0, 0, 0,
	25, 120, 24, 0, 32, 0, 0, 0, 0, 23,
	0, 0, 36, 19, 26, 27, 21, 35, 20, 0,
	0, 28, 37, 38, 0, 0, 0, 0, 22, 0,
	0, 0, 0, 18, 0, 0, 0, 0, 25, 0,
	24, 0, 32, 0, 0, 0, 0, 23, 96, 0,
	36, 19, 26, 27, 21, 35, 20, 0, 0, 28,
	37, 38, 0, 0, 0, 0, 22, 0, 0, 0,
	0, 18, 0, 0, 0, 0, 25, 68, 24, 0,
	32, 0, 0, 0, 0, 23, 0, 0, 36, 19,
	26, 27, 21, 35, 20, 0, 0, 28, 37, 38,
	0, 0, 0, 0, 22, 0, 0, 0, 0, 18,
	0, 0, 0, 0, 25, 0, 24, 66, 32, 0,
	0, 0, 0, 23, 0, 0, 36, 19, 26, 27,
	21, 35, 20, 0, 0, 28, 37, 38, 0, 0,
	0, 0, 22, 0, 0, 0, 0, 18, 0, 0,
	0, 0, 25, 0, 24, 0, 32, 0, 0, 0,
	0, 23, 0, 0, 36, 19, 26, 27, 105, 35,
	20, 0, 0, 28, 37, 38, 0, 0, 0, 0,
	22, 0, 0, 0, 0, 18, 0, 0, 0, 0,
	25, 0, 24, 0, 32, 0, 0, 137, 70, 23,
	0, 0, 36, 37, 38, 0, 0, 0, 133, 134,
	0, 0, 0, 0, 0, 135, 136, 0, 132, 25,
	0, 24, 137, 70, 177, 0, 0, 0, 37, 38,
	0, 0, 0, 133, 134, 0, 0, 0, 0, 0,
	135, 136, 0, 132, 25, 0, 24, 137, 70, 176,
	0, 0, 0, 37, 38, 0, 0, 0, 133, 134,
	0, 0, 0, 0, 0, 135, 136, 0, 132, 25,
	0, 24, 137, 70, 175, 0, 0, 0, 37, 38,
	0, 0, 0, 133, 134, 0, 0, 0, 0, 0,
	135, 136, 0, 132, 25, 0, 24, 137, 70, 174,
	0, 0, 0, 37, 38, 0, 0, 0, 133, 134,
	0, 0, 0, 0, 0, 135, 136, 0, 132, 25,
	0, 24, 137, 70, 173, 0, 0, 0, 37, 38,
	0, 0, 0, 133, 134, 0, 0, 0, 0, 0,
	135, 136, 0, 132, 25, 0, 24, 137, 70, 171,
	0, 0, 0, 37, 38, 0, 0, 0, 133, 134,
	0, 0, 0, 0, 0, 135, 136, 0, 132, 25,
	0, 24, 137, 70, 168, 0, 0, 0, 37, 38,
	0, 0, 0, 133, 134, 0, 0, 0, 0, 0,
	135, 136, 0, 132, 25, 0, 24, 137, 70, 166,
	0, 0, 0, 37, 38, 0, 0, 0, 133, 134,
	0, 0, 0, 0, 0, 135, 136, 0, 132, 25,
	0, 24, 137, 70, 165, 0, 0, 0, 37, 38,
	0, 0, 0, 133, 134, 0, 0, 0, 0, 0,
	135, 136, 0, 132, 25, 0, 24, 137, 70, 156,
	0, 0, 0, 37, 38, 0, 0, 0, 133, 134,
	0, 0, 0, 0, 0, 135, 136, 0, 132, 25,
	0, 24, 137, 70, 153, 0, 0, 0, 37, 38,
	0, 0, 0, 133, 134, 0, 0, 0, 0, 0,
	135, 136, 0, 132, 25, 0, 24, 49, 50, 0,
	56, 54, 55, 0, 51, 52,
}

var StracePact = [...]int16{
	10, -1000, 80, 313, 10, 275, 45, 23, 20, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 236, 70, -1000,
	-1000, -29, 132, -1000, 465, 427, -1000, -1000, -1000, 120,
	197, -1000, 5, -1000, -1000, 77, 73, -1000, -1000, -1000,
	-1000, 17, 40, 9, 8, 172, 4, 503, 503, 5,
	5, 5, 5, 5, 5, 5, 5, -1000, -1000, 5,
	503, 389, 503, -1000, -3, 76, -1000, 87, -1000, -1000,
	-1000, -1000, 115, 541, -39, -1000, -4, -10, 139, 102,
	60, 66, -1000, 141, -1000, -1000, 217, 151, 95, 95,
	859, 101, 187, -1000, -6, -1000, 503, -1000, 503, -1000,
	351, -1000, -1000, -18, 27, 2, 162, 116, 129, -1000,
	-1000, 845, 64, 845, 58, 57, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 159, 18, 52, 47, -1000, -1000,
	820, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 845, 795, 845, 63, 845, 62, -1000, 59,
	845, 48, 845, -1000, -1000, 770, -1000, 745, 845, 720,
	845, 845, 695, 845, 670, -1000, -1000, 645, -1000, 620,
	595, -1000, 570, -1000, -1000, -1000, -1000, -1000,
}

var StracePgo = [...]uint8{
	0, 216, 214, 3, 36, 205, 8, 1, 0, 193,
	59, 88, 191, 24, 218, 184, 182, 178, 175, 15,
}

var StraceR1 = [...]int8{
	0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 11, 11, 10,
	10, 10, 10, 10, 10, 10, 10, 10, 10, 19,
	19, 13, 13, 13, 13, 13, 13, 13, 13, 13,
	13, 14, 14, 14, 14, 14, 14, 14, 14, 14,
	14, 14, 14, 14, 16, 16, 15, 15, 9, 12,
	12, 12, 17, 17, 17, 7, 7, 6, 6, 6,
	2, 2, 2, 2, 5, 5, 4, 4, 8, 18,
	18, 18, 3, 3,
}

var StraceR2 = [...]int8{
	0, 3, 4, 5, 6, 4, 4, 4, 7, 7,
	8, 5, 5, 5, 8, 8, 9, 9, 5, 6,
	6, 6, 10, 10, 9, 9, 2, 1, 2, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	2, 1, 1, 1, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 2, 1, 2, 1, 2, 4, 4,
	4, 5, 2, 4, 1, 3, 2, 3, 4, 2,
	2, 3, 3, 4, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 2,
}

var StraceChk = [...]int16{
	-1000, -1, 7, 37, 13, 33, 36, 34, -19, -13,
	-5, -2, -17, -7, -6, -9, -18, -14, 24, 4,
	9, 7, 19, 38, 31, 29, 5, 6, 12, -15,
	-16, -12, 33, -8, -4, 8, 41, 13, 14, -1,
	36, -19, 37, 34, 34, 35, 34, 28, 17, 18,
	19, 25, 26, 20, 22, 23, 21, -7, -14, 24,
	33, 35, 40, 7, 14, -19, 32, -19, 30, -8,
	8, -4, -14, 33, 33, 36, 34, 34, 35, 35,
	13, 14, 16, 35, -13, -13, -14, -14, -14, -14,
	-14, -14, -14, -14, -19, -13, 39, -13, 35, 32,
	28, 30, 34, -19, -3, 7, 41, 35, 35, 13,
	16, 33, 8, 33, 13, 14, 16, 34, -13, -13,
	30, 34, 34, -3, 7, 7, 13, 14, 16, 13,
	-11, -10, 28, 18, 19, 25, 26, 7, -6, -7,
	-8, -4, 33, -11, 33, 8, 33, 8, 34, 8,
	33, 8, 33, 34, -10, -11, 34, -11, 33, -11,
	33, 33, -11, 33, -11, 34, 34, -11, 34, -11,
	-11, 34, -11, 34, 34, 34, 34, 34,
}

var StraceDef = [...]int8{
	0, -2, 0, 0, 0, 0, 0, 0, 0, 39,
	41, 42, 43, 44, 45, 46, 47, 48, 0, 84,
	85, 0, 0, 74, 0, 0, 89, 90, 91, 51,
	52, 53, 0, 66, 64, 88, 0, 86, 87, 26,
	1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 50, 63, 0,
	0, 80, 0, 72, 0, 0, 76, 0, 79, 67,
	88, 65, 0, 0, 0, 2, 0, 0, 0, 0,
	5, 6, 7, 0, 40, 49, 54, 55, 56, 57,
	58, 59, 60, 62, 0, 81, 0, 82, 0, 75,
	0, 77, 61, 0, 0, 92, 0, 0, 0, 18,
	3, 0, 0, 0, 11, 12, 13, 68, 83, 73,
	78, 69, 70, 93, 92, 0, 19, 20, 21, 4,
	0, 27, 29, 30, 31, 32, 33, 34, 35, 36,
	37, 38, 0, 0, 0, 0, 0, 0, 71, 0,
	0, 0, 0, 8, 28, 0, 9, 0, 0, 0,
	0, 0, 0, 0, 0, 10, 14, 0, 15, 0,
	0, 24, 0, 25, 17, 16, 22, 23,
}

var StraceTok1 = [...]int8{
	1,
}

var StraceTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44,
}

var StraceTok3 = [...]int8{
	0,
}

var StraceErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	StraceDebug        = 0
	StraceErrorVerbose = false
)

type StraceLexer interface {
	Lex(lval *StraceSymType) int
	Error(s string)
}

type StraceParser interface {
	Parse(StraceLexer) int
	Lookahead() int
}

type StraceParserImpl struct {
	lval  StraceSymType
	stack [StraceInitialStackSize]StraceSymType
	char  int
}

func (p *StraceParserImpl) Lookahead() int {
	return p.char
}

func StraceNewParser() StraceParser {
	return &StraceParserImpl{}
}

const StraceFlag = -1000

func StraceTokname(c int) string {
	if c >= 1 && c-1 < len(StraceToknames) {
		if StraceToknames[c-1] != "" {
			return StraceToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func StraceStatname(s int) string {
	if s >= 0 && s < len(StraceStatenames) {
		if StraceStatenames[s] != "" {
			return StraceStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func StraceErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !StraceErrorVerbose {
		return "syntax error"
	}

	for _, e := range StraceErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + StraceTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(StracePact[state])
	for tok := TOKSTART; tok-1 < len(StraceToknames); tok++ {
		if n := base + tok; n >= 0 && n < StraceLast && int(StraceChk[int(StraceAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if StraceDef[state] == -2 {
		i := 0
		for StraceExca[i] != -1 || int(StraceExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; StraceExca[i] >= 0; i += 2 {
			tok := int(StraceExca[i])
			if tok < TOKSTART || StraceExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if StraceExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += StraceTokname(tok)
	}
	return res
}

func Stracelex1(lex StraceLexer, lval *StraceSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(StraceTok1[0])
		goto out
	}
	if char < len(StraceTok1) {
		token = int(StraceTok1[char])
		goto out
	}
	if char >= StracePrivate {
		if char < StracePrivate+len(StraceTok2) {
			token = int(StraceTok2[char-StracePrivate])
			goto out
		}
	}
	for i := 0; i < len(StraceTok3); i += 2 {
		token = int(StraceTok3[i+0])
		if token == char {
			token = int(StraceTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(StraceTok2[1]) /* unknown char */
	}
	if StraceDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", StraceTokname(token), uint(char))
	}
	return char, token
}

func StraceParse(Stracelex StraceLexer) int {
	return StraceNewParser().Parse(Stracelex)
}

func (Stracercvr *StraceParserImpl) Parse(Stracelex StraceLexer) int {
	var Stracen int
	var StraceVAL StraceSymType
	var StraceDollar []StraceSymType
	_ = StraceDollar // silence set and not used
	StraceS := Stracercvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	Stracestate := 0
	Stracercvr.char = -1
	Stracetoken := -1 // Stracercvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		Stracestate = -1
		Stracercvr.char = -1
		Stracetoken = -1
	}()
	Stracep := -1
	goto Stracestack

ret0:
	return 0

ret1:
	return 1

Stracestack:
	/* put a state and value onto the stack */
	if StraceDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", StraceTokname(Stracetoken), StraceStatname(Stracestate))
	}

	Stracep++
	if Stracep >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceS[Stracep] = StraceVAL
	StraceS[Stracep].yys = Stracestate

Stracenewstate:
	Stracen = int(StracePact[Stracestate])
	if Stracen <= StraceFlag {
		goto Stracedefault /* simple state */
	}
	if Stracercvr.char < 0 {
		Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
	}
	Stracen += Stracetoken
	if Stracen < 0 || Stracen >= StraceLast {
		goto Stracedefault
	}
	Stracen = int(StraceAct[Stracen])
	if int(StraceChk[Stracen]) == Stracetoken { /* valid shift */
		Stracercvr.char = -1
		Stracetoken = -1
		StraceVAL = Stracercvr.lval
		Stracestate = Stracen
		if Errflag > 0 {
			Errflag--
		}
		goto Stracestack
	}

Stracedefault:
	/* default state action */
	Stracen = int(StraceDef[Stracestate])
	if Stracen == -2 {
		if Stracercvr.char < 0 {
			Stracercvr.char, Stracetoken = Stracelex1(Stracelex, &Stracercvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if StraceExca[xi+0] == -1 && int(StraceExca[xi+1]) == Stracestate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			Stracen = int(StraceExca[xi+0])
			if Stracen < 0 || Stracen == Stracetoken {
				break
			}
		}
		Stracen = int(StraceExca[xi+1])
		if Stracen < 0 {
			goto ret0
		}
	}
	if Stracen == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			Stracelex.Error(StraceErrorMessage(Stracestate, Stracetoken))
			Nerrs++
			if StraceDebug >= 1 {
				__yyfmt__.Printf("%s", StraceStatname(Stracestate))
				__yyfmt__.Printf(" saw %s\n", StraceTokname(Stracetoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for Stracep >= 0 {
				Stracen = int(StracePact[StraceS[Stracep].yys]) + StraceErrCode
				if Stracen >= 0 && Stracen < StraceLast {
					Stracestate = int(StraceAct[Stracen]) /* simulate a shift of "error" */
					if int(StraceChk[Stracestate]) == StraceErrCode {
						goto Stracestack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if StraceDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", StraceS[Stracep].yys)
				}
				Stracep--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if StraceDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", StraceTokname(Stracetoken))
			}
			if Stracetoken == StraceEofCode {
				goto ret1
			}
			Stracercvr.char = -1
			Stracetoken = -1
			goto Stracenewstate /* try again in the same state */
		}
	}

	/* reduction by production Stracen */
	if StraceDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", Stracen, StraceStatname(Stracestate))
	}

	Stracent := Stracen
	Stracept := Stracep
	_ = Stracept // guard against "declared and not used"

	Stracep -= int(StraceR2[Stracen])
	// Stracep is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if Stracep+1 >= len(StraceS) {
		nyys := make([]StraceSymType, len(StraceS)*2)
		copy(nyys, StraceS)
		StraceS = nyys
	}
	StraceVAL = StraceS[Stracep+1]

	/* consult goto table to find next state */
	Stracen = int(StraceR1[Stracen])
	Straceg := int(StracePgo[Stracen])
	Stracej := Straceg + StraceS[Stracep].yys + 1

	if Stracej >= StraceLast {
		Stracestate = int(StraceAct[Straceg])
	} else {
		Stracestate = int(StraceAct[Stracej])
		if int(StraceChk[Stracestate]) != -Stracen {
			Stracestate = int(StraceAct[Straceg])
		}
	}
	// dummy call; replaced with literal code
	switch Stracent {

	case 1:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:78
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, nil, int64(-1), true, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 2:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:80
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(-1), true, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 3:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line scanner/strace.y:83
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, -1, true, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 4:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line scanner/strace.y:88
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, nil, int64(StraceDollar[6].val_int), false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 5:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:92
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, int64(StraceDollar[4].val_int), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 6:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:94
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, int64(StraceDollar[4].val_uint), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 7:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:96
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, -1, false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 8:
		StraceDollar = StraceS[Stracept-7 : Stracept+1]
//line scanner/strace.y:98
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, int64(StraceDollar[4].val_int), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 9:
		StraceDollar = StraceS[Stracept-7 : Stracept+1]
//line scanner/strace.y:100
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, int64(StraceDollar[4].val_uint), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 10:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line scanner/strace.y:102
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", nil, int64(StraceDollar[4].val_int), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 11:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line scanner/strace.y:104
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_int), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 12:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line scanner/strace.y:106
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_uint), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 13:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line scanner/strace.y:108
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, -1, false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 14:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line scanner/strace.y:110
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_int), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 15:
		StraceDollar = StraceS[Stracept-8 : Stracept+1]
//line scanner/strace.y:112
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_uint), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 16:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line scanner/strace.y:114
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_uint), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 17:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line scanner/strace.y:116
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, "tmp", StraceDollar[2].val_types, int64(StraceDollar[5].val_int), false, true)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 18:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line scanner/strace.y:118
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, nil, StraceDollar[5].val_int, false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 19:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line scanner/strace.y:120
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_int, false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 20:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line scanner/strace.y:123
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(StraceDollar[6].val_uint), false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 21:
		StraceDollar = StraceS[Stracept-6 : Stracept+1]
//line scanner/strace.y:126
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, -1, false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 22:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line scanner/strace.y:129
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_int, false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 23:
		StraceDollar = StraceS[Stracept-10 : Stracept+1]
//line scanner/strace.y:132
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(StraceDollar[6].val_uint), false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 24:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line scanner/strace.y:135
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, StraceDollar[6].val_int, false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 25:
		StraceDollar = StraceS[Stracept-9 : Stracept+1]
//line scanner/strace.y:138
		{
			StraceVAL.val_syscall = types.NewSyscall(-1, StraceDollar[1].data, StraceDollar[3].val_types, int64(StraceDollar[6].val_uint), false, false)
			Stracelex.(*lexer).result = StraceVAL.val_syscall
		}
	case 26:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:141
		{
			call := StraceDollar[2].val_syscall
			call.Pid = StraceDollar[1].val_int
			Stracelex.(*lexer).result = call
		}
	case 27:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:144
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 28:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:145
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 29:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:148
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 30:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:149
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 31:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:150
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 32:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:151
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 33:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:152
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 34:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:153
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 35:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:154
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 36:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:155
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 37:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:156
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 38:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:157
		{
			StraceVAL.val_parenthetical = types.NewParenthetical()
		}
	case 39:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:161
		{
			types := make([]types.Type, 0)
			types = append(types, StraceDollar[1].val_type)
			StraceVAL.val_types = types
		}
	case 40:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:162
		{
			StraceDollar[1].val_types = append(StraceDollar[1].val_types, StraceDollar[3].val_type)
			StraceVAL.val_types = StraceDollar[1].val_types
		}
	case 41:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:166
		{
			StraceVAL.val_type = StraceDollar[1].val_buf_type
		}
	case 42:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:167
		{
			StraceVAL.val_type = StraceDollar[1].val_field
		}
	case 43:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:168
		{
			StraceVAL.val_type = StraceDollar[1].val_pointer_type
		}
	case 44:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:169
		{
			StraceVAL.val_type = StraceDollar[1].val_array_type
		}
	case 45:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:170
		{
			StraceVAL.val_type = StraceDollar[1].val_struct_type
		}
	case 46:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:171
		{
			StraceVAL.val_type = StraceDollar[1].val_call
		}
	case 47:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:172
		{
			StraceVAL.val_type = StraceDollar[1].val_ip_type
		}
	case 48:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:173
		{
			StraceVAL.val_type = StraceDollar[1].val_type
		}
	case 49:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:174
		{
			StraceVAL.val_type = types.NewDynamicType(StraceDollar[1].val_type, StraceDollar[3].val_type)
		}
	case 50:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:175
		{
			StraceVAL.val_type = StraceDollar[2].val_array_type
		}
	case 51:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:179
		{
			StraceVAL.val_type = types.NewExpression(StraceDollar[1].val_type)
		}
	case 52:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:180
		{
			StraceVAL.val_type = types.NewExpression(StraceDollar[1].val_type)
		}
	case 53:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:181
		{
			StraceVAL.val_type = types.NewExpression(StraceDollar[1].val_macro)
		}
	case 54:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:182
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.OR, StraceDollar[3].val_type))
		}
	case 55:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:183
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.AND, StraceDollar[3].val_type))
		}
	case 56:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:184
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.LSHIFT, StraceDollar[3].val_type))
		}
	case 57:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:185
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.RSHIFT, StraceDollar[3].val_type))
		}
	case 58:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:186
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.LOR, StraceDollar[3].val_type))
		}
	case 59:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:187
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.LAND, StraceDollar[3].val_type))
		}
	case 60:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:188
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.LEQUAL, StraceDollar[3].val_type))
		}
	case 61:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:189
		{
			StraceVAL.val_type = StraceDollar[2].val_type
		}
	case 62:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:190
		{
			StraceVAL.val_type = types.NewExpression(types.NewBinop(StraceDollar[1].val_type, types.TIMES, StraceDollar[3].val_type))
		}
	case 63:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:191
		{
			StraceVAL.val_type = types.NewExpression(types.NewUnop(StraceDollar[2].val_type, types.ONESCOMP))
		}
	case 64:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:194
		{
			i := make(types.Ints, 1)
			i[0] = StraceDollar[1].val_int_type
			StraceVAL.val_type = i
		}
	case 65:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:195
		{
			StraceVAL.val_type = append(StraceDollar[1].val_type.(types.Ints), StraceDollar[2].val_int_type)
		}
	case 66:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:198
		{
			f := make(types.Flags, 1)
			f[0] = StraceDollar[1].val_flag_type
			StraceVAL.val_type = f
		}
	case 67:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:199
		{
			StraceVAL.val_type = append(StraceDollar[1].val_type.(types.Flags), StraceDollar[2].val_flag_type)
		}
	case 68:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:202
		{
			StraceVAL.val_call = types.NewCallType(StraceDollar[1].data, StraceDollar[3].val_types)
		}
	case 69:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:205
		{
			StraceVAL.val_macro = types.NewMacroType(StraceDollar[1].data, StraceDollar[3].val_types)
		}
	case 70:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:206
		{
			StraceVAL.val_macro = types.NewMacroType(StraceDollar[1].data, nil)
		}
	case 71:
		StraceDollar = StraceS[Stracept-5 : Stracept+1]
//line scanner/strace.y:207
		{
			StraceVAL.val_macro = types.NewMacroType(StraceDollar[4].data, nil)
		}
	case 72:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:210
		{
			StraceVAL.val_pointer_type = types.NullPointer()
		}
	case 73:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:211
		{
			StraceVAL.val_pointer_type = types.NewPointerType(StraceDollar[2].val_uint, StraceDollar[4].val_type)
		}
	case 74:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:212
		{
			StraceVAL.val_pointer_type = types.NullPointer()
		}
	case 75:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:215
		{
			arr := types.NewArrayType(StraceDollar[2].val_types)
			StraceVAL.val_array_type = arr
		}
	case 76:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:216
		{
			arr := types.NewArrayType(nil)
			StraceVAL.val_array_type = arr
		}
	case 77:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:219
		{
			StraceVAL.val_struct_type = types.NewStructType(StraceDollar[2].val_types)
		}
	case 78:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:220
		{
			StraceVAL.val_struct_type = types.NewStructType(StraceDollar[2].val_types)
		}
	case 79:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:221
		{
			StraceVAL.val_struct_type = types.NewStructType(nil)
		}
	case 80:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:224
		{
			StraceVAL.val_field = types.NewField(StraceDollar[1].data, nil)
		}
	case 81:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:225
		{
			StraceVAL.val_field = types.NewField(StraceDollar[1].data, StraceDollar[3].val_type)
		}
	case 82:
		StraceDollar = StraceS[Stracept-3 : Stracept+1]
//line scanner/strace.y:226
		{
			StraceVAL.val_field = types.NewField(StraceDollar[1].data, StraceDollar[3].val_type)
		}
	case 83:
		StraceDollar = StraceS[Stracept-4 : Stracept+1]
//line scanner/strace.y:227
		{
			StraceVAL.val_field = types.NewField(StraceDollar[1].data, StraceDollar[4].val_type)
		}
	case 84:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:230
		{
			StraceVAL.val_buf_type = types.NewBufferType(StraceDollar[1].data)
		}
	case 85:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:231
		{
			StraceVAL.val_buf_type = types.NewBufferType(StraceDollar[1].data)
		}
	case 86:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:235
		{
			StraceVAL.val_int_type = types.NewIntType(StraceDollar[1].val_int)
		}
	case 87:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:236
		{
			StraceVAL.val_int_type = types.NewIntType(int64(StraceDollar[1].val_uint))
		}
	case 88:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:239
		{
			StraceVAL.val_flag_type = types.NewFlagType(StraceDollar[1].data)
		}
	case 89:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:242
		{
			StraceVAL.val_ip_type = types.NewIpType(StraceDollar[1].data)
		}
	case 90:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:243
		{
			StraceVAL.val_ip_type = types.NewIpType(StraceDollar[1].data)
		}
	case 91:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:244
		{
			StraceVAL.val_ip_type = types.NewIpType(StraceDollar[1].data)
		}
	case 92:
		StraceDollar = StraceS[Stracept-1 : Stracept+1]
//line scanner/strace.y:247
		{
			ids := make([]*types.BufferType, 0)
			ids = append(ids, types.NewBufferType(StraceDollar[1].data))
			StraceVAL.val_identifiers = ids
		}
	case 93:
		StraceDollar = StraceS[Stracept-2 : Stracept+1]
//line scanner/strace.y:248
		{
			StraceDollar[2].val_identifiers = append(StraceDollar[2].val_identifiers, types.NewBufferType(StraceDollar[1].data))
			StraceVAL.val_identifiers = StraceDollar[2].val_identifiers
		}
	}
	goto Stracestack /* stack new state and value */
}
